# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# this comment

trigger:
- api-service
pr: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '--configuration $(buildConfiguration)'
    zipAfterPublish: true
    projects: '**/ViewzApi.csproj'
  displayName: 'DotNet publish api and app + zip'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(54320e88-cfc4-4aec-90cf-a5c188c75dd0)'
    appType: 'webAppLinux'
    appName: 'viewzapicanary'
    package: '$(System.DefaultWorkingDirectory)/ViewzApi/**/*.zip'